# Generated by Django 3.0.4 on 2020-03-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='award_pics/'),
        ),
    ]
